[programs.localnet]
biowatchcare = "24paEKyzz4aoBDmpdGVyC4Larnp7Bwka95TkgLHoLTiC"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
build = "anchor build"
test = "npm run test"

[toolchain]
anchor_version = "0.31.1"
