[programs.localnet]
biowatchcare = "FhXSGiUzcvtAVqXM8tyy1HzUf4mFxkUQEvwgmjLRgow3"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
build = "anchor build"

[toolchain]
anchor_version = "0.31.1"
